[[links]]
title = "Blog"
url = "https://blog.evanchen.cc/"
menu-position = 6
indent = true

[[links]]
title = "CV"
url = "upload/public-CV.pdf"
menu-position = 4
indent = true

[[links]]
title = "ELMO"
url = "https://elmo.evanchen.cc/"
menu-position = 36
indent = true
