[global]
disable = [
  "MD025", # Allow multiple h1
  "MD026", # Permit punctuation in heading
  "MD033", # Permit inline HTML
  "MD041", # Allow first line to be anything (not just h1)
  "MD051", # Anchors like #L-1 are not detectable
]

extend-enable = ["MD060"]
exclude = [".git", "LICENSE.md"]
respect-gitignore = true

[MD013]
line-length = 160
code-blocks = false
tables = false
headings = false

[MD030]
ol-single = 2
ol-multi = 2
