import olympiad;
size(7cm);
pair B = origin, C=(5,0), A = (4,5);
draw(A--B--C--cycle); dot(A^^B^^C);
path w = circumcircle(A,B,C); draw(w);
pair O = circumcenter(A,B,C);
path w1 = circumcircle(B,O,C);
pair o = circumcenter(B,O,C);
path t = (O--o);
real x = circumradius(B,O,C);
path T=shift((0,-x))*t;
pair [] x=intersectionpoints (T, w1);
pair P = x[0]; dot(P);
draw(A--P^^B--P^^C--P);
pair [] y=intersectionpoints (A--P,B--C);
pair D = y[0]; dot(D);
real d = length(C-D);
path b=shift((-d,0))*(A--C);
pair [] z=intersectionpoints(b, A--B);
pair F = z[0]; dot(F); draw(D--F, gray);
real g = length(B-D);
path c=shift((g,0))*(A--B);
pair [] w=intersectionpoints(c, A--C);
pair E = w[0]; dot(E); draw(D--E, gray);
label("$A$", A, NE); label("$B$", B, W); label("$C$", C, SE); label("$P$", P, S);
label("$D$", D, NW); label("$E$", E, NE); label("$F$", F, W);
markscalefactor=0.07;
/* draw(anglemark(C,B,A));
draw(scale(0.9)*Label("B"),0.8*ENE);
draw(scale(1.1)*anglemark(P,B,C));
draw(scale(0.9)*Label("A"),0.8*ESE);
draw(anglemark(B,C,P));
draw(scale(0.9)*Label("A"),C, 4*WSW);
draw(anglemark(A,C,B));
draw(scale(0.9)*Label("C"),C, 4*NW);
draw(anglemark(B,A,D));
draw(scale(0.9)*Label("$\alpha$"),A, 5*SSW);
draw(anglemark(D,A,C));
draw(scale(0.9)*Label("$\beta$"),A, 5*S); */
