name: "Conventional commits"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  main:
    uses: vEnhance/dotfiles@6fe4f49fd29e1e09fab6bbc586044293694514b7 # main
